//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional
namespace EmployeeManagement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "cafe",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    name = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    description = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    location = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    logo = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_cafe", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "employee",
                columns: table => new
                {
                    id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    name = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    email = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    phone_number = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: false),
                    gender = table.Column<int>(type: "int", nullable: false),
                    start_date = table.Column<DateTime>(type: "Date", nullable: true),
                    cafe_id = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    cafe_id1 = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_employee", x => x.id);
                    table.ForeignKey(
                        name: "FK_Employee_Cafe",
                        column: x => x.cafe_id,
                        principalTable: "cafe",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_employee_cafe_cafe_id",
                        column: x => x.cafe_id1,
                        principalTable: "cafe",
                        principalColumn: "id");
                });

            migrationBuilder.InsertData(
                table: "cafe",
                columns: new[] { "id", "description", "location", "logo", "name" },
                values: new object[,]
                {
                    { new Guid("24dad7de-c26f-4d2c-81d3-22422e088c65"), "Test edscription DEF", "Galle", null, "Cafe DEF" },
                    { new Guid("517f64d9-09b3-4632-8af1-0ee4c7b21ccb"), "Test edscription ABC", "Colombo", null, "Cafe ABC" }
                });

            migrationBuilder.InsertData(
                table: "employee",
                columns: new[] { "id", "cafe_id1", "cafe_id", "gender", "name", "start_date", "email", "phone_number" },
                values: new object[,]
                {
                    { "UI1FF17YL", null, null, 0, "Employee_1", null, "abc@mail.com", "97654321" },
                    { "UITN4VM3N", null, null, 1, "Employee_2", null, "edf@mail.com", "87654321" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_employee_cafe_id",
                table: "employee",
                column: "cafe_id1");

            migrationBuilder.CreateIndex(
                name: "ix_employee_current_cafe",
                table: "employee",
                column: "cafe_id");

            migrationBuilder.CreateIndex(
                name: "ix_employee_email",
                table: "employee",
                column: "email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_employee_phone_number",
                table: "employee",
                column: "phone_number",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "employee");

            migrationBuilder.DropTable(
                name: "cafe");
        }
    }
}
